name: azure-voting-app-redis
trigger:
- main
variables:
- template: variables/vars.yml
stages:
- template: stages/ci.yml
  parameters:
    resourceGroup: ${{ variables.resourceGroup }}
    containerRegistry: ${{ variables.containerRegistry }}
    serviceConnection: ${{ variables.serviceConnection }}
- template: stages/cd.yml
  parameters:
    resourceGroup: ${{ variables.resourceGroup }}
    aksCluster: ${{ variables.aksCluster }}
    serviceConnection: ${{ variables.serviceConnection }}