name: azure-voting-app-redis
trigger:
- main
variables:
- template: variables/vars.yml
stages:
- template: stages/ci.yml
  parameters:
    serviceConnection: ${{ variables.serviceConnection }}
    resourceGroup: ${{ variables.resourceGroup }}
    containerRegistry: ${{ variables.containerRegistry }}
    containerRepository: ${{ variables.containerRepository }}
- template: stages/cd.yml
  parameters:
    serviceConnection: ${{ variables.serviceConnection }}
    resourceGroup: ${{ variables.resourceGroup }}
    aksCluster: ${{ variables.aksCluster }}
    kubernetesNamespace: ${{ variables.kubernetesNamespace }}
    containerRegistry: ${{ variables.containerRegistry }}
    containerRepository: ${{ variables.containerRepository }}
    teamEmail: ${{ variables.teamEmail }}
