parameters:
- name: resourceGroup
  type: string
- name: aksCluster
  type: string
- name: serviceConnection
  type: string
  
#get artifact
#create imagepullsecret
#deploy, overriding container

stages:
- stage: CD
  dependsOn: CI
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: Manifest
    - task: AzureCLI@2
      displayName: Get AKS credentials
      inputs:
        azureSubscription: ${{ parameters.serviceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER_NAME)
    - task: Kubernetes@1
      displayName: Deploy to AKS
      inputs:
        connectionType: Azure Resource Manager
        azureSubscription: ${{ parameters.serviceConnection }}
        azureResourceGroup: ${{ parameters.resourceGroup }}
        kubernetesCluster: ${{ parameters.aksCluster }}
        namespace: azure-vote
        command: apply
        arguments: -f $(dependencies.CI.outputs['BuildAndPush.value'])"