parameters:
- name: containerRegistry
  type: string
- name: containerRepository
  type: string

stages:
- stage: CI
  jobs:
  - job: Tests
    steps:
    - pwsh: |
        Write-Output "Run tests here"
  - job: BuildAndPush
    dependsOn: Tests
    steps:
    - task: Docker@2
      displayName: Build and push to ACR
      inputs:
        containerRegistry: ${{ parameters.containerRegistry }}
        repository: ${{ parameters.containerRepository }}
        dockerfile: azure-vote/Dockerfile
        command: buildAndPush
        tags: |
          $(Build.BuildId)
    - pwsh: |
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $manifestName = "voteapp_$(Build.BuildId)_$timestamp.yaml"
        Copy-Item azure-vote-all-in-one-redis.yaml $manifestName
        Write-Output "##vso[task.setvariable variable=value;isoutput=true]$manifestName"
      name: ManifestName
    - publish: $(ManifestName.value)
      artifact: Manifest
