parameters:
- name: resourceGroup
  type: string
- name: containerRegistry
  type: string
- name: serviceConnection
  type: string

#docker build
#use $(Build.BuildId)
#push
#generate string for manifest name -> setvariable
  #format: voteapp_<buildid>_<datetime>
#generate manifest, renamed to voteapp_<buildid>_<datetime> per above
#add manifest to artifacts

stages:
- stage: CI
  jobs:
  - job: Tests
    steps:
    - bash: |
        echo "Run tests here"
  - job: BuildAndPush
    dependsOn: Tests  # because we can't run parallel jobs for free
    steps:
    - task: Docker@2
      displayName: Build and push to ACR
      inputs:
        containerRegistry: ${{ parameters.containerRegistry }}
        repository: azure-vote
        dockerfile: azure-vote/Dockerfile
        command: buildAndPush
        tags: |
          $(Build.BuildId)
    - bash: |
        timestamp=$(date +%Y%m%d%H%M%S)
        echo "##vso[task.setvariable variable=value;isoutput=true]voteapp_$(Build.BuildId)_$timestamp"
      name: ManifestName
    - publish: azure-vote-all-in-one-redis.yaml
      artifact: Manifest
